### ISSUE TITLE
add Debian-Version

### ISSUE THREAD

**Issue by strowi** [webdevops/php-docker-boilerplate#16]
Hi,

since Debian is quite a common hosting-solution, how about adding a Debian-Version ?

regards,
strowi

**Comment by mblaschke** [comment]
with refactoring, see https://github.com/webdevops/php-docker-boilerplate/tree/feature/refactoring

**Comment by mblaschke** [comment]
Debian-8 is now building with refactoring (available in some hours)

**Comment by mblaschke** [comment]
Also added debian-7 and debian-8-php7 :)
