### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by dgram** [webdevops/php-docker-boilerplate#24]
Hi,

i have an question about the [https://github.com/webdevops/php-docker-boilerplate/blob/develop/etc/cron/crontab](crontab) - is the cronjob yet initialized/useable?

regards

**Comment by mblaschke** [comment]
It should be working, yes

PS: you can chat with us at slack: https://webdevops.io/slack/

**Comment by mblaschke** [comment]
Currently it's a full crontab (eg. `/etc/cron.d/foobar`) so include a user :)

**Comment by dgram** [comment]
hi, thx for the fast response.
i've tried it, it works - thx =)

next time i have an issue, i use the chat

thx, regards
