### ISSUE TITLE
php blackfire is not working for ubuntu images

### ISSUE THREAD

**Issue by rabe69** [webdevops/php-docker-boilerplate#29]
Because of a wrong path inside provision/roles/boilerplate-main-development/tasks/bootstrap.yml the main build fails:
"Failed to find required executable rpm"

It should be look like this:
```
---

- include: bootstrap/php-blackfire/debian.yml
  when: ansible_distribution == 'CentOS' and PROVISION.install.phpBlackfire is defined and PROVISION.install.phpBlackfire

- include: bootstrap/php-blackfire/debian.yml
  when: ansible_os_family == 'Debian' and PROVISION.install.phpBlackfire is defined and PROVISION.install.phpBlackfire

- include: bootstrap/php.xdebug.yml
  when: PROVISION.install.phpXdebug is defined and PROVISION.install.phpXdebug
```

Additional, the provisioning script "provision/roles/boilerplate-main-development/tasks/bootstrap/php-blackfire/debian.yml" only installs the blackfire-php (probe), but not the blackfire-agent (blackfire-agent and cli-tools) package.
To get blackfire working, both packages are needed and an unique server/client id and token, which can be get from the blackfire.io webpage, must be set.

As far as I see, there is currently no possibility to set this parameters in any yml file.

The whole install process is described on this page:
https://blackfire.io/docs/up-and-running/installation

There is also a complete docker setup for php blackfire available:
https://blackfire.io/docs/integrations/docker

**Comment by mblaschke** [comment]
With images published this night new images with blackfire are available.
See https://github.com/webdevops/Dockerfile/issues/116 and https://github.com/webdevops/Dockerfile/issues/113

For documentation see http://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-dev.html
