### ISSUE TITLE
Memcached extension failed in php

### ISSUE THREAD

**Issue by dgram** [webdevops/php-docker-boilerplate#31]
hi,

i've installed the new version 5.0.0 with the "webdevops/php-apache:debian-8-php7" template.
i activated the memcached part in the docker-compose.yml file.

but when i check if the php memcached extension is installed, i cant find any extension

regards

**Comment by mblaschke** [comment]
Should be fixed with rebuild tonight.

**Comment by dgram** [comment]
thx
