### ISSUE TITLE
Nginx Symfony3 Debian 8 

### ISSUE THREAD

**Issue by 4dr3n4l1n3** [webdevops/php-docker-boilerplate#33]
Hi,
When i try to connect to app_dev.php i get this Alert !

"An error occurred while loading the web debug toolbar (404: Not Found).

Do you want to open the profiler?"
![screenshot from 2016-03-29 18 16 33](https://cloud.githubusercontent.com/assets/12262847/14117004/87d169bc-f5da-11e5-82b3-ceb4ff687c09.png)
and when i press OK i get this url, app_dev.php/_profiler/290fc5 with "File not found. " message.

the config that i use 

- docker-compose.development.yml
- webdevops/php-nginx:debian-8 image

**Comment by mblaschke** [comment]
It's working here.
* How old is the webdevops/php-nginx:debian-8 image?
* Which boilerplate version do you use?
* Which `etc/environment.yml` settings are used?
* Any errors shown with `docker-compose logs app`?

**Comment by 4dr3n4l1n3** [comment]
Hi mblashke,

- How old is the webdevops/php-nginx:debian-8 image?
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
webdevops/php-nginx                  debian-8            7f5632c53de7        20 hours ago        856 MB

- Which boilerplate version do you use?
I use the latest version from your git repository
https://github.com/webdevops/php-docker-boilerplate

- Which etc/environment.yml settings are used?
only the default server and mysql setting are activated 
# Webserver
# General
WEB_DOCUMENT_ROOT=/app/
WEB_DOCUMENT_INDEX=index.php
CLI_SCRIPT=php /app/index.php
# MySQL settings
MYSQL_ROOT_PASSWORD=dev
MYSQL_USER=dev
MYSQL_PASSWORD=dev
MYSQL_DATABASE=database

`Starting phpdockerboilerplatemaster_storage_1
Recreating phpdockerboilerplatemaster_mysql_1
Recreating phpdockerboilerplatemaster_app_1
Attaching to phpdockerboilerplatemaster_storage_1, phpdockerboilerplatemaster_mysql_1, phpdockerboilerplatemaster_app_1
mysql_1   | 2016-03-29T20:57:50.629840Z 0 [Note] mysqld (mysqld 5.7.11-log) starting as process 1 ...
mysql_1   | 2016-03-29T20:57:50.638625Z 0 [Note] InnoDB: PUNCH HOLE support available
mysql_1   | 2016-03-29T20:57:50.638647Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mysql_1   | 2016-03-29T20:57:50.638651Z 0 [Note] InnoDB: Uses event mutexes
mysql_1   | 2016-03-29T20:57:50.638655Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mysql_1   | 2016-03-29T20:57:50.638658Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.8
mysql_1   | 2016-03-29T20:57:50.638661Z 0 [Note] InnoDB: Using Linux native AIO
mysql_1   | 2016-03-29T20:57:50.638822Z 0 [Note] InnoDB: Number of pools: 1
mysql_1   | 2016-03-29T20:57:50.638906Z 0 [Note] InnoDB: Using CPU crc32 instructions
mysql_1   | 2016-03-29T20:57:50.644500Z 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mysql_1   | 2016-03-29T20:57:50.656415Z 0 [Note] InnoDB: Completed initialization of buffer pool
mysql_1   | 2016-03-29T20:57:50.658743Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1   | 2016-03-29T20:57:50.671235Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1   | 2016-03-29T20:57:50.733800Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1   | 2016-03-29T20:57:50.733914Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1   | 2016-03-29T20:57:51.225759Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1   | 2016-03-29T20:57:51.228165Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1   | 2016-03-29T20:57:51.228202Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1   | 2016-03-29T20:57:51.229606Z 0 [Note] InnoDB: 5.7.11 started; log sequence number 11993240
mysql_1   | 2016-03-29T20:57:51.230402Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1   | 2016-03-29T20:57:51.231385Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1   | 2016-03-29T20:57:51.232417Z 0 [ERROR] Could not use /dev/stderr for logging (error 2 - No such file or directory). Turning logging off for the server process. To turn it on again: fix the cause, then either restart the query logging by using "SET GLOBAL SLOW_QUERY_LOG=ON" or restart the MySQL server.
mysql_1   | 2016-03-29T20:57:51.237257Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160329 20:57:51
mysql_1   | 2016-03-29T20:57:51.238090Z 0 [Warning] Failed to set up SSL because of the following SSL library error: SSL context is not usable without certificate and private key
mysql_1   | 2016-03-29T20:57:51.238161Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1   | 2016-03-29T20:57:51.238234Z 0 [Note] IPv6 is available.
mysql_1   | 2016-03-29T20:57:51.238444Z 0 [Note]   - '::' resolves to '::';
mysql_1   | 2016-03-29T20:57:51.238473Z 0 [Note] Server socket created on IP: '::'.
mysql_1   | 2016-03-29T20:57:51.284884Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1   | 2016-03-29T20:57:51.284927Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1   | 2016-03-29T20:57:51.287959Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1   | 2016-03-29T20:57:51.296509Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1   | 2016-03-29T20:57:51.298387Z 0 [Note] mysqld: ready for connections.
mysql_1   | Version: '5.7.11-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
app_1     | 
app_1     | PLAY ***************************************************************************
app_1     | 
app_1     | TASK [setup] *******************************************************************
app_1     | ok: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/bootstrap.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/bootstrap/services.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/bootstrap/cron.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/bootstrap/php.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/bootstrap/web.apache.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/bootstrap/web.nginx.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/entrypoint.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/entrypoint/mysql.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : Deploy root my.cnf] ***********************************
app_1     | changed: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : Deploy user my.cnf] ***********************************
app_1     | changed: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include] **********************************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main/tasks/entrypoint/php.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main : include_vars] *****************************************
app_1     | ok: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : include_vars] *****************************************
app_1     | ok: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main : Configure environment variables from DOCKER_ENVIRONMENT for php-fpm (pool www.conf)] ***
app_1     | changed: [localhost] => (item={'value': u'dev', 'key': u'MYSQL_PASSWORD'})
app_1     | skipping: [localhost] => (item={'value': u'', 'key': u'FTP_USER'}) 
app_1     | skipping: [localhost] => (item={'value': u'', 'key': u'POSTGRES_USER'}) 
app_1     | changed: [localhost] => (item={'value': u'dev', 'key': u'MYSQL_ROOT_PASSWORD'})
app_1     | changed: [localhost] => (item={'value': u'dev', 'key': u'SYMFONY_ENV'})
app_1     | skipping: [localhost] => (item={'value': u'', 'key': u'POSTGRES_PASSWORD'}) 
app_1     | changed: [localhost] => (item={'value': u'Development/Docker', 'key': u'TYPO3_CONTEXT'})
app_1     | skipping: [localhost] => (item={'value': u'', 'key': u'FTP_PATH'}) 
app_1     | skipping: [localhost] => (item={'value': u'', 'key': u'MAIL_GATEWAY'}) 
app_1     | changed: [localhost] => (item={'value': u'dev', 'key': u'MYSQL_USER'})
app_1     | skipping: [localhost] => (item={'value': u'', 'key': u'FTP_PASSWORD'}) 
app_1     | changed: [localhost] => (item={'value': u'database', 'key': u'MYSQL_DATABASE'})
app_1     | changed: [localhost] => (item={'value': u'0', 'key': u'SYMFONY_DEBUG'})
app_1     | changed: [localhost] => (item={'value': u'dev', 'key': u'CAKE_ENV'})
app_1     | changed: [localhost] => (item={'value': u'php /app/index.php', 'key': u'CLI_SCRIPT'})
app_1     | changed: [localhost] => (item={'value': u'Development', 'key': u'YII_ENVIRONMENT'})
app_1     | 
app_1     | TASK [boilerplate-main-development : include] **********************************
app_1     | included: /opt/docker/provision/roles/boilerplate-main-development/tasks/bootstrap.yml for localhost
app_1     | 
app_1     | TASK [boilerplate-main-development : include] **********************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main-development : include] **********************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | TASK [boilerplate-main-development : include] **********************************
app_1     | skipping: [localhost]
app_1     | 
app_1     | PLAY RECAP *********************************************************************
app_1     | localhost                  : ok=16   changed=3    unreachable=0    failed=0   
app_1     | 
app_1     | 2016-03-29 20:57:57,548 CRIT Set uid to user 0
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/cron.conf" during parsing
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/dnsmasq.conf" during parsing
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/postfix.conf" during parsing
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/nginx.conf" during parsing
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/php-fpm.conf" during parsing
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/syslog-ng.conf" during parsing
app_1     | 2016-03-29 20:57:57,549 WARN Included extra file "/opt/docker/etc/supervisor.d/ssh.conf" during parsing
app_1     | 2016-03-29 20:57:57,570 INFO RPC interface 'supervisor' initialized
app_1     | 2016-03-29 20:57:57,571 CRIT Server 'unix_http_server' running without any HTTP authentication checking
app_1     | 2016-03-29 20:57:57,571 INFO supervisord started with pid 1
app_1     | 2016-03-29 20:57:58,574 INFO spawned: 'syslogd' with pid 262
app_1     | 2016-03-29 20:57:58,577 INFO spawned: 'dnsmasqd' with pid 263
app_1     | 2016-03-29 20:57:58,580 INFO spawned: 'nginxd' with pid 264
app_1     | 2016-03-29 20:57:58,582 INFO spawned: 'php-fpmd' with pid 265
app_1     | 2016-03-29 20:57:58,588 INFO spawned: 'php-fpm-log-slow' with pid 266
app_1     | 2016-03-29 20:57:58,593 INFO spawned: 'php-fpm-log-access' with pid 268
app_1     | 2016-03-29 20:57:58,596 INFO spawned: 'php-fpm-log-error' with pid 269
app_1     | 2016-03-29 20:57:58,598 INFO spawned: 'php-fpm-log-fpm' with pid 271
app_1     | 2016-03-29 20:57:58,600 INFO spawned: 'crond' with pid 272
app_1     | 2016-03-29 20:57:58,604 INFO spawned: 'postfixd' with pid 277
app_1     | 2016-03-29 20:57:58,607 INFO spawned: 'postfix-log' with pid 278
app_1     | 2016-03-29 20:57:58,614 INFO spawned: 'syslog-log' with pid 281
app_1     | 2016-03-29 20:57:58,663 INFO success: dnsmasqd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,663 INFO success: nginxd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,664 INFO success: php-fpmd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,664 INFO success: php-fpm-log-slow entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,664 INFO success: php-fpm-log-access entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,664 INFO success: php-fpm-log-error entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,664 INFO success: php-fpm-log-fpm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,665 INFO success: crond entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,665 INFO success: postfixd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | 2016-03-29 20:57:58,665 INFO success: postfix-log entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
app_1     | Replacing "<DOCUMENT_INDEX>" with "index.php" (case sensitive) (partial words matched)
app_1     | Replacing "<DOCUMENT_ROOT>" with "/app/" (case sensitive) (partial words matched)
app_1     | Replacing "<ALIAS_DOMAIN>" with "*.vm" (case sensitive) (partial words matched)
app_1     | Replacing "<SERVERNAME>" with "04577f2585b3" (case sensitive) (partial words matched)
app_1     | 2016-03-29 20:57:59,795 INFO success: syslogd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1     | 2016-03-29 20:57:59,796 INFO success: syslog-log entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
app_1     | [syslog] Mar 29 20:58:01 04577f2585b3 cron[272]: (*system*docker-boilerplate) INSECURE MODE (group/other writable) (/etc/cron.d/docker-boilerplate)
`

**Comment by mblaschke** [comment]
With Symfony you should set (default directory layout of Symfony)
`WEB_DOCUMENT_ROOT=/app/web/`
and
`WEB_DOCUMENT_INDEX=app_dev.php`

Please try again :)

**Comment by 4dr3n4l1n3** [comment]
many many thanks for your help =)

**Comment by TrogWarZ** [comment]
Sorry for asking here, but i think this is maybe relevant.

Prerequisites. I'm using Symfony3 and it requires `/app/var/cache` + `/app/var/logs` to be writeable but by default there aren't. If i do `chmod 1777 -R /app/var` manually as root inside image – it's ok.

My related question 1 is: where i need to put this code to automate this? Maybe, in `/Dockerfile.development` one more RUN-section, right? Just noobie here.

Unrelated question 2: host machine doesn't has even php installed. Where i need to script installing composer (and some php extensions from pecl needed to project)? Have no idea )-:
