### ISSUE TITLE
Port 80 and 443

### ISSUE THREAD

**Issue by mpastas** [webdevops/php-docker-boilerplate#59]
Is there any configuration to expose the port 80 and 443?

I've tried with docker compose:

```
ports:
  - "80:80"
  - "443:443"
```

**Comment by mblaschke** [comment]
Should be working without problems, what are you using as Docker host?

**Comment by mpastas** [comment]
Hi Markus, Virtualbox on Mac.

**Comment by mblaschke** [comment]
Any error message?
Please keep in mind that the exposed port is only available on the VM, not on the mac.

**Comment by mpastas** [comment]
Right, so it is working there and I would like to expose it on the mac with the port 80, is there any chance to do it using the configs?

**Comment by mblaschke** [comment]
Not on docker scope because docker can only control the host on which it is running (the linux host).

If you want it on the mac use the port mapping/forwarding from your virtualization.

**Comment by mpastas** [comment]
What about a Linux OS? Same results in there..

**Comment by mblaschke** [comment]
Docker only exposes the port on the linux host where Docker is running so it depends if you're running Docker on the bare metal host (port is available directly on 127.0.0.1) or in a virtualization (same problem) :)

**Comment by mblaschke** [comment]
If docker (running in a VM) would have access to your macOS this would be a real security issue if it can control the OS outside of the virtualization ;)

**Comment by mpastas** [comment]
:D Got it! thanks for the quick responses!

**Comment by mblaschke** [comment]
You're welcome :)
