### ISSUE TITLE
Set up many virtual hosts in main app container

### ISSUE THREAD

**Issue by danwyry** [webdevops/php-docker-boilerplate#80]
Hi, Is there a way to set up many virtual hosts pointing to to diferent paths in app/ through image or environment configuration?
I'm very new to Docker and have been trying to do this with this php-docker-boilerplate (which I found very usefull btw) and couln't figure it out.

**Comment by hhoechtl** [comment]
No that's not possible without building a custom image.

But usually you would use 1 container per vhost. If you're concerned about port 80 being occupied by the first container, take a look at https://github.com/jwilder/nginx-proxy or https://jtreminio.com/blog/traefik-on-docker-for-web-developers/
